### PR TITLE
Adds missed refactoring

### PR DESCRIPTION
**Pull request by tiesont**
Also corrects error caused by unassigned default value for 'setting'.

### CODE REVIEW

**Comment by tiesont** [comment]
> Also corrects error caused by unassigned default value for 'setting'.

I'm not sure why, but I was getting a compiler error until I defaulted it to false. Of course, I may have fixed that prior to fixing the undefined `GetAppSetting()` reference. I can switch it to var if you prefer.

**Comment by stevenbey** [comment]
>  I can switch it to var if you prefer.

I know it's a little pedantic but yes please.  Thanks

**Comment by tiesont** [comment]
> I know it's a little pedantic

Not at all. I did check, and yes, with the correction to use the indexers, it does allow the uninitialized value of setting. So, the error I was seeing before was a side-effect of GetAppSetting being undefined. Would you prefer

    var setting = false;

or

    bool setting;

I can do either.

**Comment by stevenbey** [comment]
I'd prefer

    bool setting;

Thanks

**Pull request merged**
